#!/usr/bin/env python

from arm_composites_manufacturing_process import ProcessController
import rospy
import time


def main():
    rospy.init_node("pick_and_place_panel", anonymous=True)
    
    p=ProcessController(disable_ft=False)
    
    # Wait for payload messages to arrive
    time.sleep(0.5)
    
    rospy.loginfo("Begin panel pick and place script")
    p.reset_position()
    p.plan_pickup_prepare('leeward_tip_panel')
    
    p.move_pickup_prepare()

    p.plan_pickup_lower()
    p.move_pickup_lower()
    '''
    p.plan_pickup_grab_first_step()
    p.move_pickup_grab_first_step()
    p.plan_pickup_grab_second_step()
    p.move_pickup_grab_second_step()
    p.plan_pickup_raise()
    p.move_pickup_raise()
    
    p.plan_transport_payload('panel_nest_leeward_mid_panel_target')
    p.move_transport_payload()
    
    rospy.loginfo("End panel pick and place script")
    '''
if __name__ == '__main__':
    main()
